version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: barobar_postgres
    environment:
      POSTGRES_USER: barobar
      POSTGRES_PASSWORD: barobar
      POSTGRES_DB: barobar_monitoring
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
